### PR TITLE
practice GitHub Flow

### PR DESCRIPTION
**Pull request by tonomoshia**
This pull request attempts to demonstrate GitHHub Flow, using both the command line interface and [github.com](http://www.github.com).
## Checklist
- [x] overview of concepts
- [ ] make sure I can 'git push'

### CODE REVIEW

**Comment by tonomoshia** [comment]
My bio is going to be :trophy: legendary.

**Comment by tonomoshia** [comment]
Please comment on #3 if you haven't already.

**Comment by mixolidia** [comment]
Hi @tonomoshia,
Or may I call you Elizabeth? :smiley:
Looks good 👍 !

**Comment by tonomoshia** [comment]
@mixolidia Yes Elizabeth is fine! :100:

**Pull request merged**
